### PR TITLE
making country context and adding new nav

### PR DESCRIPTION
**Pull request by drifter089**
image
image
image

### CODE REVIEW

**Review by yerbol-akhmetov — COMMENTED** [review]
Thanks, @drifter089. Making the left side panel always visible gave some value and filled the space, thanks. I have a question what happens when you click show network statistics? Can you show that too

**Comment by drifter089** [comment]
image
it looks like this 
country level statics will be avilable always and are now full page

**Comment by drifter089** [comment]
image

used country polygons made by @BryanFran 
now ntework veiw is optional and can be toggeled

image

@yerbol-akhmetov  and @ekatef

**Comment by yerbol-akhmetov** [comment]
> image it looks like this country level statics will be avilable always and are now full page

Thanks, @drifter089. Not a big priority, but it would be good to make bar chart smaller, thinner.

**Comment by yerbol-akhmetov** [comment]
> image
> 
> used country polygons made by @BryanFran now ntework veiw is optional and can be toggeled
> 
> image
> 
> @yerbol-akhmetov and @ekatef

Thanks, @drifter089. I like such button. Can we move it to navigation panel and make it like tab? Country view and Network view. But again it is not priority, just cosmetics.
image

**Comment by drifter089** [comment]
@yerbol-akhmetov ,
this looks good but country and network veiw is specific to this page so keeping it out of navigation

image

I have made the charts fit better

**Comment by drifter089** [comment]
image

**Comment by yerbol-akhmetov** [comment]
> @yerbol-akhmetov , this looks good but country and network veiw is specific to this page so keeping it out of navigation
> 
> image
> 
> I have made the charts fit better

Ok, then I see. Thanks.

**Comment by ekatef** [comment]
Thanks a lot @drifter089!!
@yerbol-akhmetov appreciate your great review work and completely agree with the comments

@drifter089 I wonder how do you see putting together the country navigation panel and  the control elements for the left plot in the scenario tab? Is the idea to put them side-by-side, something like:
image

**Review by yerbol-akhmetov — APPROVED** [review]
Thank you, @drifter089. Approving the changes!

**Comment by ekatef** [comment]
> I have just remove it for now @ekatef , but we can do whatever way we like

Agree, let's go step-by-step 😄 
Great work, and feel free to merge!

**Pull request merged**
